---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    get:
      summary: List all products
      tags:
      - Products
      responses:
        '200':
          description: products found
    post:
      summary: Creates a product
      tags:
      - Products
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
              example: Product Test 1
            price:
              type: number
              format: float
              description: A positive number
              example: 10.0
          required:
          - name
          - price
      responses:
        '201':
          description: product created
        '422':
          description: invalid request
  "/api/v1/products/{id}":
    get:
      summary: Retrieves a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '200':
          description: product found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              price:
                type: number
                format: float
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - name
            - price
            - created_at
            - updated_at
    put:
      summary: Updates a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      - name: product
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
              example: Product Updated Test 1
            price:
              type: number
              format: float
              description: A positive number
              example: 20.0
          required: []
      responses:
        '200':
          description: product updated
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              price:
                type: number
                format: float
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - name
            - price
            - created_at
            - updated_at
    delete:
      summary: Deletes a product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '204':
          description: product deleted
  "/api/v1/stock_items":
    get:
      summary: List all stock_items
      tags:
      - Stock Items
      responses:
        '200':
          description: stock items found
    post:
      summary: Creates a stock item
      tags:
      - Stock Items
      parameters:
      - name: stock_item
        in: body
        schema:
          type: object
          properties:
            product_id:
              type: integer
              example: 1
            store_id:
              type: integer
              example: 1
            items:
              type: integer
              example: 5
              default: 0
          required:
          - product_id
          - store_id
      responses:
        '201':
          description: stock item created
        '422':
          description: invalid request
  "/api/v1/stock_items/{id}":
    get:
      summary: Retrieves a stock item
      tags:
      - Stock Items
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '200':
          description: stock item found
          schema:
            type: object
            properties:
              id:
                type: integer
              product_id:
                type: integer
              store_id:
                type: integer
              items:
                type: integer
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - product_id
            - store_id
            - items
            - created_at
            - updated_at
  "/api/v1/stock_items/{id}/add_items":
    put:
      summary: Add items to a Stock Item
      tags:
      - Stock Items
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      - name: stock_item
        in: body
        schema:
          type: object
          properties:
            items:
              type: integer
              example: 3
          required:
          - items
      responses:
        '200':
          description: stock item updated
          schema:
            type: object
            properties:
              id:
                type: integer
              product_id:
                type: integer
              store_id:
                type: integer
              items:
                type: integer
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - product_id
            - store_id
            - items
            - created_at
            - updated_at
        '422':
          description: error adding stock item
  "/api/v1/stock_items/{id}/remove_items":
    put:
      summary: Remove items from a Stock Item
      tags:
      - Stock Items
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      - name: stock_item
        in: body
        schema:
          type: object
          properties:
            items:
              type: integer
              example: 3
          required:
          - items
      responses:
        '200':
          description: stock item updated
          schema:
            type: object
            properties:
              id:
                type: integer
              product_id:
                type: integer
              store_id:
                type: integer
              items:
                type: integer
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - product_id
            - store_id
            - items
            - created_at
            - updated_at
        '422':
          description: error removing stock item
  "/api/v1/stores":
    get:
      summary: List all stores
      tags:
      - Stores
      responses:
        '200':
          description: stores found
    post:
      summary: Creates a store
      tags:
      - Stores
      parameters:
      - name: store
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
              example: Store Test 1
            address:
              type: string
              example: Road Test
          required:
          - name
          - address
      responses:
        '201':
          description: store created
        '422':
          description: invalid request
  "/api/v1/stores/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '200':
          description: store found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: stirng
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - name
            - address
            - created_at
            - updated_at
    put:
      summary: Updates a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      - name: store
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
              example: Store Updated Test 1
            address:
              type: string
              example: Road Test
          required: []
      responses:
        '200':
          description: store updated
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
            required:
            - id
            - name
            - address
            - created_at
            - updated_at
    delete:
      summary: Deletes a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
      responses:
        '204':
          description: store deleted
consumes:
- application/json
produces:
- application/json
